version: '3.3'
services:
    product-service:
        container_name: 'rad_product'
        environment:
            PORT: '8080'
            NODE_ENV: 'development'
        build: .
        ports:
            - '8080:8080'
        volumes:
            - .:/usr/src/app
        command: node_modules/.bin/nodemon --watch . --delay 2.5 --exec 'ts-node' ./index.ts
        depends_on:
            - product-db
    product-db:
        container_name: 'rad_db'
        image: mysql:5.7
        restart: always
        network_mode: bridge
        environment:
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'root'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'root'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - 3313:3306
        expose:
            # Opens port 3306 on the container
            - 3306
            # Where our data will be persisted
        volumes:
            - product-db:/var/lib/mysql
    # Names our volume
volumes:
    product-db:
